name: Build AURGH

on: [push, pull_request]

jobs:
  clang:
    name: "Build AURGH (meson)"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < required.txt

      - name: Build AURGH
        run: |
          make setup
          make compile
