name: Build AURGH

on: [push, pull_request]

jobs:
  gtk3:
    name: "Build AURGH - gtk3"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < required-gtk3.txt

      - name: clang
        run: |
          CXX=clang++ CXX_LD=lld meson setup -Dbuildtype=debugoptimized clang_target
          meson compile -C clang_target

      - name: gcc
        run: |
          meson setup -Dbuildtype=debugoptimized gcc_target
          meson compile -C gcc_target

  gtk4:
    name: "Build AURGH - gtk4"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < required-gtk4.txt

      - name: clang
        run: |
          CXX=clang++ CXX_LD=lld meson setup -Dbuildtype=debugoptimized -Duse-gtk4=true clang_target
          meson compile -C clang_target

      - name: gcc
        run: |
          meson setup -Dbuildtype=debugoptimized -Duse-gtk4=true gcc_target
          meson compile -C gcc_target