name: GTK4 Build

on: [push, pull_request]

jobs:
  clang:
    name: "Build AURGH - clang"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < required-gtk4.txt

      - name: compile
        run: |
          CXX=clang++ CXX_LD=lld meson setup -Dbuildtype=debugoptimized -Duse-gtk4=true clang_target
          meson compile -C clang_target
  gcc:
    name: "Build AURGH - gcc"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < required-gtk4.txt

      - name: compile
        run: |
          meson setup -Dbuildtype=debugoptimized -Duse-gtk4=true gcc_target
          meson compile -C gcc_target