name: GTK4 Build

on: [push, pull_request]

jobs:
  clang:
    name: "Build AURGH - clang"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < assets/required-gtk4.txt

      - name: compile
        run: |
          make GTK_VERSION=4
  gcc:
    name: "Build AURGH - gcc"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < assets/required-gtk4.txt

      - name: compile
        run: |
          make CXX=g++ CXX_LD=bfd GTK_VERSION=4
