name: GTK4 Build

on:
  push:
    paths:
      - '**/meson.build'
      - '**/meson_options.txt'
      - '**/*.meson'
      - '.github/workflows/*.yml'
      - '**/*.jsonc'
      - '**/*.cc'
      - '**/*.hh'

permissions:
  contents: read

jobs:
  clang:
    name: "Build AURGH - clang"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-${{ hashFiles('assets/required-gtk4.txt') }}
          restore-keys: |
            ${{ runner.os }}-pacman-

      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < assets/required-gtk4.txt

      - name: compile
        run: |
          CXX=clang++ CXX_LD=lld meson setup -Dgtk-version=4 target
          meson compile -C target

  gcc:
    name: "Build AURGH - gcc"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v4

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-${{ hashFiles('assets/required-gtk4.txt') }}
          restore-keys: |
            ${{ runner.os }}-pacman-

      - name: Install dependencies
        shell: bash
        run: |
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
          pacman -Syyu --noconfirm --noprogressbar --needed - < assets/required-gtk4.txt

      - name: compile
        run: |
          CXX=g++ CXX_LD=bfd meson setup -Dgtk-version=4 target
          meson compile -C target
